# https://github.com/sxyazi/yazi/tree/main/yazi-config/preset

[manager]
show_hidden = true
show_symlink = true
sort_by = "natural"
ratio = [2, 4, 6]


[opener]
open = [
  { run = 'xdg-open "$1"', desc = "Open", for = "linux" },
  { run = 'open "$@"', desc = "Open", for = "macos" },
]
